### ISSUE TITLE
Misaligned keybinding box (English version, page 24)

### ISSUE THREAD

**Issue by mmarshall540** [Emacs101/howm-manual#5]
Hi, and thank you for this excellent resource.

In making my way through the English manual, I noticed this minor graphical issue, which I thought to bring to your attention.

![Screenshot from 2024-05-25 13-24-10](https://github.com/Emacs101/howm-manual/assets/62682447/79b65b6c-c43b-49a4-9319-b2213b0662e7)

I skimmed through the rest of the manual looking for any other examples of this and couldn't find any.

Thank you again.

**Comment by Emacs101** [comment]
Hi @mmarshall540 
Thank you so much for noticing this typographical inaccuracy! I have updated the manual file.
